### ISSUE TITLE
An error occurred in on_message: 'Behavior' object has no attribute 'probability_to_reply' (Line: 1199 in on_message, bot.py )

### ISSUE THREAD

**Issue by windetrsfugwq** [altoiddealer/ad_discordbot#2]
ERROR [2024-03-15 16:55:04]: An error occurred while processing "on_message" request: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1) (Line: 1254 in on_message_gen, bot.py )
ERROR [2024-03-15 16:55:04]: An error occurred while processing a main task: name 'embed' is not defined (Line: 1602 in process_tasks, bot.py )
ERROR [2024-03-15 16:55:05]: An error occurred in on_message: 'Behavior' object has no attribute 'probability_to_reply' (Line: 1199 in on_message, bot.py )

**Comment by altoiddealer** [comment]
I appologize for the issue - I had pushed a bad commit earlier today.

I believe my most recent commit (update for bot.py) will resolve that error.

let me know if it persists

**Comment by windetrsfugwq** [comment]
it persists but ill do a pull for all the new stuff too

**Comment by windetrsfugwq** [comment]
ERROR [2024-03-17 01:01:23]: An error occurred while processing a main task: name 'embed' is not defined (Line: 1600 in process_tasks, bot.py )
ERROR [2024-03-17 01:01:25]: An error occurred in on_message: 'Behavior' object has no attribute 'probability_to_reply' (Line: 1201 in on_message, bot.py )

**Comment by windetrsfugwq** [comment]
> it persists but ill do a pull for all the new stuff too

all of it still is after new pull

**Comment by altoiddealer** [comment]
I’m sorry the issue is persisting, and I know it’s currently a bit inconvenient to update when anything changes other than bot.py

I likely will not have this fixed until tomorrow.

in the meantime, I recommend using bot.py from 3 days ago, [this one here](https://github.com/altoiddealer/ad_discordbot/commit/b94a6c92afd4716d68eac0e4c0168d485542ec8e).  Click Raw File in the upper right and then save it.

if your error changes, please let me know as I suspect it may be something different than the error is currentystatingy

**Comment by altoiddealer** [comment]
Awhile back, I noticed that the original author (I’ll blame him!) had misspelled “probability” in the key “probability_to_reply”.  That may be the problem if your key still has the spelling error.  Check your applicable characters, base_settings, and activesettings.

**Comment by windetrsfugwq** [comment]
idk if this is new or a part of the same thing 
ERROR [2024-03-18 21:49:32]: An error occurred while processing "on_message" request: 'user_bio' (Line: 1202 in on_message_gen, bot.py )

**Comment by altoiddealer** [comment]
Closing this as completed

https://github.com/altoiddealer/ad_discordbot/commit/33a0224c9706326a65335a51286c5812b93bf374
